version: '3.8'
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    volumes:
      - .:/var/www:rw
      - ./logs/nginx:/var/log/nginx/:rw
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    container_name: php
    restart: always

    ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      -   '5431:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data: